server:  
  port: 8090
  
spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/lly?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root  
    password: 123  
    driverClassName: com.mysql.cj.jdbc.Driver
 